const ActionTypes = {
    MAAK_SPELERS: "MAAK_SPELERS",
    INITIALIZEER_SPELERS: "INITIALIZEER_SPELERS",
    // SECONDE_MINDER: "SECONDE_MINDER",
    UPDATE_TIJD: "UPDATE_TIJD",
    VOLGENDE_SPELER: "VOLGENDE_SPELER",
    START_TIMER: "START_TIMER",
    STOP_TIMER: "STOP_TIMER"
};


export default ActionTypes;